apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: temporaryroleapprovals.roles.k8su.io
spec:
  group: roles.k8su.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                temporaryRoleRequest:
                  type: string
                approvedBy:
                  type: string
                approvedSource:
                  type: string
      additionalPrinterColumns:
        - name: Request
          type: string
          description: The name of the temporary role
          jsonPath: .spec.temporaryRoleRequest
        - jsonPath: .spec.approvedBy
          name: by
          type: string
        - jsonPath: .spec.approvedSource
          name: source
          type: string
  scope: Namespaced
  names:
    plural: temporaryroleapprovals
    singular: temporaryroleapproval
    kind: TemporaryRoleApproval
    shortNames:
    - tra