apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: temporaryroles.roles.k8su.io
spec:
  group: roles.k8su.io
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                role:
                  type: string
                leaseTimeSeconds:
                  type: integer
                # name of service account to assign to
                assignToServiceAccount:
                  type: string
      additionalPrinterColumns:
      - name: Role
        type: string
        description: The k8s role to bind to
        jsonPath: .spec.role
      - name: SvcAct
        type: string
        description: The k8s service account to bind to
        jsonPath: .spec.assignToServiceAccount
  scope: Namespaced
  names:
    plural: temporaryroles
    singular: temporaryrole
    kind: TemporaryRole
    shortNames:
    - tr
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: temporaryrolerequests.roles.k8su.io
spec:
  group: roles.k8su.io
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                temporaryRole:
                  type: string
      additionalPrinterColumns:
      - name: TemporaryRole
        type: string
        description: The name of the temporary role
        jsonPath: .spec.temporaryRole
  scope: Namespaced
  names:
    plural: temporaryrolerequests
    singular: temporaryrolerequest
    kind: TemporaryRoleRequest
    shortNames:
    - trr