apiVersion: roles.k8su.io/v1alpha1
kind: TemporaryRole
metadata:
  name: crd-tr-1
  namespace: k8su
  labels:
    k8su: "yes"
spec:
  role: "k8su-pod-reader"
  leaseTimeSeconds: 10
  subject:
    serviceAccount: "k8su-svc-account"
---
apiVersion: roles.k8su.io/v1alpha1
kind: TemporaryRole
metadata:
  name: crd-tr-2
  namespace: k8su
  labels:
    k8su: "yes"
spec:
  role: "k8su-pod-reader"
  leaseTimeSeconds: 10
  subject:
    user: "k8su-svc-account"
---
apiVersion: roles.k8su.io/v1alpha1
kind: TemporaryRole
metadata:
  name: crd-tr-3
  namespace: k8su
  labels:
    k8su: "yes"
spec:
  role: "k8su-pod-reader"
  leaseTimeSeconds: 10
  subject:
    group: "k8su-svc-account"
---
apiVersion: roles.k8su.io/v1alpha1
kind: TemporaryRoleRequest
metadata:
  name: lease-a-bit
  namespace: k8su
spec:
  temporaryRole: temp-role-assignment