apiVersion: roles.k8su.io/v1alpha1
kind: TemporaryRole
metadata:
  name: crd-tr-1
  namespace: k8su
  labels:
    k8su: "yes"
spec:
  role: "k8su-pod-reader"
  leaseTimeSeconds: 10
  subject:
    serviceAccount: "k8su-svc-account"
    user: "abc"
    group: "abc"