apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8su-controller-svc-account
  namespace: k8su
  labels:
    app: k8su-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8su-controller-cluster-role
  labels:
    app: k8su-controller
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["roles.k8su.io"]
  resources: ["temporaryroles", "temporaryrolerequests", "temporaryroleapprovals"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8su-controller-binding
subjects:
- kind: ServiceAccount
  name: k8su-controller-svc-account
  namespace: k8su
roleRef:
  kind: ClusterRole
  name: k8su-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
--- 
# sample description for roles to assign temporarily
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8su-controller-regular-role
  namespace: k8su
  labels:
    app: k8su-controller
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "bind"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["bind"]
  resourceNames: ["k8su-pod-reader"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8su-controller-binding
  namespace: k8su
subjects:
- kind: ServiceAccount
  name: k8su-controller-svc-account
  namespace: k8su
roleRef:
  kind: Role
  name: k8su-controller-regular-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8su-controller
  name: k8su-controller
  namespace: k8su
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8su-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8su-controller
    spec:
      serviceAccountName: k8su-controller-svc-account
      containers:
      - image: 192.168.1.10:5000/k8su/k8su-controller:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 2
          exec:
            command:
              - "true"
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 5
        name: k8su-controller
        readinessProbe:
          failureThreshold: 2
          exec:
            command:
              - "true"
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
      terminationGracePeriodSeconds: 5