apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8su-mutatingwebhook
  labels:
    app: k8su-mutatingwebhook
webhooks:
  - name: k8su.io.k8su.k8su-mutatingwebhook
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    matchPolicy: Equivalent
    failurePolicy: Fail
    clientConfig:
      caBundle: CA_BUNDLE
      service:
        name: k8su-mutatingwebhook
        namespace: k8su
        path: "/mutate"
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["roles.k8su.io"]
        apiVersions: ["v1alpha1"]
        resources: ["temporaryrolerequests", "temporaryroleapprovals"]
        scope: "Namespaced"