apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8su-mutatingwebhook
  name: k8su-mutatingwebhook
  namespace: k8su
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8su-mutatingwebhook
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8su-mutatingwebhook
    spec:
      containers:
      - image: 192.168.1.10:5000/k8su/k8su-mutatingwebhook:latest
        imagePullPolicy: Always
        env:
          - name: CERT_KEY
            value: /etc/certs/tls.key
          - name: CERT
            value: /etc/certs/tls.crt
        volumeMounts:
          - mountPath: /etc/certs
            name: certs
            readOnly: true
        ports:
          - containerPort: 443
            protocol: TCP
        livenessProbe:
          failureThreshold: 2
          exec:
            command:
              - "true"
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 5
        name: k8su-controller
        readinessProbe:
          failureThreshold: 2
          exec:
            command:
              - "true"
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
      volumes:
        - name: certs
          secret:
            secretName: k8su-mutatingwebhook-tls-secret 
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: k8su-mutatingwebhook
spec:
  type: ClusterIP
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: k8su-mutatingwebhook