apiVersion: roles.k8su.io/v1alpha1
kind: TemporaryRole
metadata:
  name: temp-role-assignment
  namespace: k8su
  labels:
    k8su: "yes"
spec:
  role: "k8su-pod-reader"
  leaseTimeSeconds: 100
  subject:
    serviceAccount: "k8su-svc-account"
---
apiVersion: roles.k8su.io/v1alpha1
kind: TemporaryRoleRequest
metadata:
  name: lease-a-bit-longer
  namespace: k8su
spec:
  temporaryRole: temp-role-assignment