apiVersion: v1
kind: Namespace
metadata:
  name: k8su
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8su-svc-account
  namespace: k8su
  labels:
    k8su: "yes"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8su-pod-reader
  namespace: k8su
  labels:
    k8su: "yes"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]