apiVersion: v1
kind: Namespace
metadata:
  name: k8su
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8su-svc-account
  namespace: k8su
  labels:
    k8su: "yes"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8su-pod-reader
  namespace: k8su
  labels:
    k8su: "yes"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: roles.k8su.io/v1alpha1
kind: TemporaryRole
metadata:
  name: temp-role-assignment
  namespace: k8su
  labels:
    k8su: "yes"
spec:
  role: "k8su-pod-reader"
  leaseTimeSeconds: 10 # 2 minutes
  assignToServiceAccount: "k8su-svc-account"
---
apiVersion: roles.k8su.io/v1alpha1
kind: TemporaryRoleRequest
metadata:
  name: lease-a-bit
  namespace: k8su
spec:
  temporaryRole: temp-role-assignment